services:
  splunk:
    image: splunk/splunk:9.1
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Monitoring123!
    ports:
      - "8000:8000"
    volumes:
      - splunk-data:/opt/splunk/var
    restart: unless-stopped

volumes:
  splunk-data:
